version: '3.8'

services:
  raksha_app:
    build: .
    container_name: raksha_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - raksha_db

  raksha_db:
    image: mysql:5.7
    container_name: raksha_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raksha_ai
      MYSQL_USER: raksha_user
      MYSQL_PASSWORD: raksha_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: raksha_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: raksha_db
      MYSQL_ROOT_PASSWORD: root


volumes:
  db_data: